name: Docker Compose Check

on:
  push:
    paths:
      - 'compose-project/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Docker Compose
        run: |
          cd compose-project
          docker-compose up -d
          sleep 5
          docker-compose ps
          docker-compose logs stats
