name: Web Project CI

on:
  push:
    paths:
      - 'web-project/**' # Запускать только при изменениях в этой папке

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-web-check ./web-project

    - name: Test - Check if index.html exists in image
      run: |
        docker run --rm my-web-check ls /usr/share/nginx/html/index.html
        echo "Файл index.html на месте, тест пройден!"
